[package]
name = "wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
long_int = {git = "https://github.com/LaGipeR/LongInt"}
openssl = "0.10.55"
hex = "0.4.3"